from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 461, 41))
        self.label.setObjectName("label")
        self.tblListele = QtWidgets.QTableWidget(self.centralwidget)
        self.tblListele.setGeometry(QtCore.QRect(40, 410, 721, 221))
        self.tblListele.setRowCount(100)
        self.tblListele.setColumnCount(6)
        self.tblListele.setObjectName("tblListele")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 350, 61, 25))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(700, 20, 194, 33))
        self.label_9.setObjectName("label_9")
        self.lblSeciliOgrenci = QtWidgets.QLineEdit(self.centralwidget)
        self.lblSeciliOgrenci.setGeometry(QtCore.QRect(700, 60, 287, 22))
        self.lblSeciliOgrenci.setObjectName("lblSeciliOgrenci")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(300, 200, 217, 24))
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 231, 24))
        self.label_5.setObjectName("label_5")
        self.lblNumarasi = QtWidgets.QLineEdit(self.centralwidget)
        self.lblNumarasi.setGeometry(QtCore.QRect(170, 70, 209, 22))
        self.lblNumarasi.setObjectName("lblNumarasi")
        self.lblAdi = QtWidgets.QLineEdit(self.centralwidget)
        self.lblAdi.setGeometry(QtCore.QRect(170, 110, 209, 22))
        self.lblAdi.setObjectName("lblAdi")
        self.lblSoyadi = QtWidgets.QLineEdit(self.centralwidget)
        self.lblSoyadi.setGeometry(QtCore.QRect(170, 150, 209, 22))
        self.lblSoyadi.setObjectName("lblSoyadi")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 60, 124, 35))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 124, 56))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 100, 124, 119))
        self.label_3.setObjectName("label_3")
        self.cbDersAdi = QtWidgets.QComboBox(self.centralwidget)
        self.cbDersAdi.setGeometry(QtCore.QRect(300, 230, 277, 22))
        self.cbDersAdi.setObjectName("cbDersAdi")
        self.cbDersAdi.addItem("")
        self.cbDersAdi.addItem("")
        self.cbDersAdi.addItem("")
        self.cbDersAdi.addItem("")
        self.cbDersAdi.addItem("")
        self.cbDersAdi.addItem("")
        self.cbDersAdi.addItem("")
        self.cbBolumu = QtWidgets.QComboBox(self.centralwidget)
        self.cbBolumu.setGeometry(QtCore.QRect(30, 230, 241, 22))
        self.cbBolumu.setObjectName("cbBolumu")
        self.cbBolumu.addItem("")
        self.btnEkle = QtWidgets.QPushButton(self.centralwidget)
        self.btnEkle.setGeometry(QtCore.QRect(30, 290, 172, 28))
        self.btnEkle.setObjectName("btnEkle")
        self.btnGuncelle = QtWidgets.QPushButton(self.centralwidget)
        self.btnGuncelle.setGeometry(QtCore.QRect(730, 100, 241, 41))
        self.btnGuncelle.setObjectName("btnGuncelle")
        self.btnSil = QtWidgets.QPushButton(self.centralwidget)
        self.btnSil.setGeometry(QtCore.QRect(200, 290, 211, 28))
        self.btnSil.setObjectName("btnSil")
        self.btnListele = QtWidgets.QPushButton(self.centralwidget)
        self.btnListele.setGeometry(QtCore.QRect(410, 290, 241, 28))
        self.btnListele.setObjectName("btnListele")
        self.btnTemizle = QtWidgets.QPushButton(self.centralwidget)
        self.btnTemizle.setGeometry(QtCore.QRect(790, 590, 181, 37))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnTemizle.setFont(font)
        self.btnTemizle.setObjectName("btnTemizle")
        self.btnDuzenle = QtWidgets.QPushButton(self.centralwidget)
        self.btnDuzenle.setGeometry(QtCore.QRect(760, 140, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnDuzenle.setFont(font)
        self.btnDuzenle.setObjectName("btnDuzenle")
        self.cbDersSec = QtWidgets.QComboBox(self.centralwidget)
        self.cbDersSec.setGeometry(QtCore.QRect(150, 350, 277, 22))
        self.cbDersSec.setObjectName("cbDersSec")
        self.cbDersSec.addItem("")
        self.cbDersSec.addItem("")
        self.cbDersSec.addItem("")
        self.cbDersSec.addItem("")
        self.cbDersSec.addItem("")
        self.cbDersSec.addItem("")
        self.cbDersSec.addItem("")
        self.btnDersListele = QtWidgets.QPushButton(self.centralwidget)
        self.btnDersListele.setGeometry(QtCore.QRect(150, 380, 277, 28))
        self.btnDersListele.setObjectName("btnDersListele")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1307, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.cbDersAdi.setCurrentIndex(-1)
        self.cbBolumu.setCurrentIndex(-1)
        self.cbDersSec.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">Öğrenci Bilgi Sistemi</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "DERS SEÇ:"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">Öğrenci:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Ders Seçiniz:"))
        self.label_5.setText(_translate("MainWindow", "Bölüm Seçiniz:"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Öğrencinin Numarası:</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Öğrencinin Adı:</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Öğrenci Soyadı:</p></body></html>"))
        self.cbDersAdi.setItemText(0, _translate("MainWindow", "Görsel Programlama"))
        self.cbDersAdi.setItemText(1, _translate("MainWindow", "Açık Kaynak Web Programlama"))
        self.cbDersAdi.setItemText(2, _translate("MainWindow", "Ağ Temelleri"))
        self.cbDersAdi.setItemText(3, _translate("MainWindow", "Mobil Programlama"))
        self.cbDersAdi.setItemText(4, _translate("MainWindow", "İnternet Programcılığı"))
        self.cbDersAdi.setItemText(5, _translate("MainWindow", "Veritabanı Yönetim Sistemleri Uygulamaları"))
        self.cbBolumu.setItemText(0, _translate("MainWindow", "Bilgisayar Teknolojileri"))
        self.btnEkle.setText(_translate("MainWindow", "Öğrenci Ekle"))
        self.btnGuncelle.setText(_translate("MainWindow", "Öğrenci Güncelle"))
        self.btnSil.setText(_translate("MainWindow", "Öğrenci Sil"))
        self.btnListele.setText(_translate("MainWindow", "Öğrenci Listele"))
        self.btnTemizle.setText(_translate("MainWindow", "Temizle"))
        self.btnDuzenle.setText(_translate("MainWindow", "Düzenle"))
        self.cbDersSec.setItemText(0, _translate("MainWindow", "Görsel Programlama"))
        self.cbDersSec.setItemText(1, _translate("MainWindow", "Açık Kaynak Web Programlama"))
        self.cbDersSec.setItemText(2, _translate("MainWindow", "Ağ Temelleri"))
        self.cbDersSec.setItemText(3, _translate("MainWindow", "Mobil Programlama"))
        self.cbDersSec.setItemText(4, _translate("MainWindow", "İnternet Programcılığı"))
        self.cbDersSec.setItemText(5, _translate("MainWindow", "Veritabanı Yönetim Sistemleri Uygulamaları"))
        self.btnDersListele.setText(_translate("MainWindow", "Listele"))
